// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtjizbosebhpuldwtpcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0aml6Ym9zZWJocHVsZHd0cGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Nzk4NzMsImV4cCI6MjA1ODU1NTg3M30.qNtdWp0yh5CJJDcVwKUy3bube0AQVN0LTeZCiYwmmso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);